name: Go

on:
  push:
    branches: [ "main", "create-jobs" ]
  pull_request:
    branches: [ "create-jobs" ]

jobs:

  lint:
    name: Check errors and start tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Run lint
      uses: golangci/golangci-lint-action@v6.0.1
    - name: Test
      run: go test
  
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ikiruh/cicd-final

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
